### ISSUE TITLE
TypeError: can't convert Hash into String when using serialize on attributes

### ISSUE THREAD

**Issue by fffanatics** [Shopify/identity_cache#113]
I have the following class:

    class Project < ActiveRecord::Base
      include IdentityCache
      attr_accessible :metadata,
      serialize :metadata, JSON
    end

When you fetch the object for the first time, it works fine. If you fetch it a second time, it throws the following error:

    TypeError: can't convert Hash into String
    from ~/.rvm/gems/ruby-1.9.3-p484/gems/json-1.8.1/lib/json/common.rb:155:in `initialize'

Any way to get it to respect the JSON serialization of attributes?

Thanks!

**Comment by camilo** [comment]
I'll close in the hopes that the problem "went away" I have never seen it myself in prod over the last year (or ever really).

**Comment by gonzalog** [comment]
The same on Rails 4.2.10, with Ruby 2.3.1p112
