### ISSUE TITLE
Reduce the IdentityCache.should_cache? checks to a single layer of abstraction

### ISSUE THREAD

**Issue by fbogsany** [Shopify/identity_cache#162]
We should look into whether we can reduce the `IdentityCache.should_cache?` checks to a single layer of abstraction rather than having it duplicated across multiple layers (e.g. `IdentityCache` and `QueryApi`).

Follow-up from #154

**Comment by camilo** [comment]
@fbogsany iamma close this, reopen if you think we need to.
