### ISSUE TITLE
cache_has_many failing to reflect

### ISSUE THREAD

**Issue by xxx** [Shopify/identity_cache#168]
Hi,

I'm upgrading an app from Rails 4.0 to 4.1, and upgraded identity_cache with it. We have a `cache_has_many` set up, which is now failing due to a `reflect_on_association` call returning nil in the `add_parent_expiry_hook` method, even if the `:inverse_name` option is given.

This call is only returning nil during startup - at that point it correctly returns the necessary association, so it looks like some ordering problem is at the root of this. I'm not sure how to go about debugging this.

**Comment by dylanahsmith** [comment]
We are on rails 4.1, so that isn't the problem.

If `reflect_on_association` is returning `nil` then it should be raising an InverseAssociationError now, which happens when `:inverse_name` isn't correct.  Make sure the child class has an association with the same name given in the `:inverse_name` option.

**Comment by dylanahsmith** [comment]
Closing since it sounds like this is fixed

**Comment by quekshuy** [comment]
Seeing the same issue with Rails 4.2.1. It's quite inconsistent -- happening in an environment other than our development environment. Have also tried with `inverse_name` option without any effect. Would appreciate if anyone knows anything.

**Comment by quekshuy** [comment]
OK here's how I fixed this:

in config/environments/<environment>.rb,  look for

```
config.eager_loading = false # set from true to false
```

This might have repercussions on performance though.

**Comment by coffeebite** [comment]
Seeing this problem again in Rails 5, but only when running jobs through Backburner.
Any idea under what circumstances reflections maybe returning nil?
