### ISSUE TITLE
Misleading [IDC id mismatch] error: UUID

### ISSUE THREAD

**Issue by niiamon** [Shopify/identity_cache#176]
If you're using UUID as primary keys for models, then every time you access a cached object, IDC will complain of [IDC id mismatch] because of https://github.com/Shopify/identity_cache/blob/85b1c21fdc3f208eaabcc86b8f686751050cc8b9/lib/identity_cache/query_api.rb#L31.

That line does a `to_i` on the `object .id`. I think this will fail in the case of UUIDs.

**Comment by lanrion** [comment]
Maybe we can use `Digest::MD5.hexdigest` to switch and compare.

**Comment by kidlab** [comment]
IMHO, why don't we use `to_s` to compare them?

**Comment by dylanahsmith** [comment]
> IMHO, why don't we use `to_s` to compare them?

Go for it.  A proper type cast would be more general, but usually the primary key will be a string or integer, and it will work in both of those cases.

**Comment by lanrion** [comment]
Several days, fix by `to_s`  in https://github.com/lanrion/identity_cache/commit/d0a7b91021ef9069b2f89fce722c4872c5b6355a , my database use UUID for primary key, and now it looks nice.
