### ISSUE TITLE
Weird SQL syntax error.

### ISSUE THREAD

**Issue by stillwyw** [Shopify/identity_cache#181]
I'm just trying with identity_cache today. And having this weird error:

    ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "FROM"
    LINE 1: SELECT   FROM "towns"  WHERE "towns"."absid" = 'UCL222062' L...
                 ^
    : SELECT   FROM "towns"  WHERE "towns"."absid" = 'UCL222062' LIMIT 1):
      app/controllers/towns_controller.rb:8:in `show'

As you can see in the SQL query, thats a blank between `SELECT` and `FROM`. When I use `find_by_absid` instead of `fetch_by_absid` then no issue.

I'm using:

postgresql 9.1 with postgis
activerecord-postgis-adapter
rails 3.2.6
ruby 1.9.3

Thanks :)

**Comment by camilo** [comment]
PG is tricky, since we (maintainers) don't really run PG in production. I'l close since this is more than 1yr old.
