### ISSUE TITLE
NoMethodError undefined method `type_cast' for ActiveRecord::ConnectionAdapters::PostgreSQLColumn

### ISSUE THREAD

**Issue by alexvodovoz** [Shopify/identity_cache#196]
I'm using activerecord-4.2.0 and it looks like the type_cast method isn't supported anymore.  

type_cast is being referenced in the find_batch method in identity_cache-0.2.2/lib/identity_cache/query_api.rb

Is identity cache compatible with the latest version of rails(4.2.0)?

**Comment by dylanahsmith** [comment]
No, it is not yet compatible with rails 4.2.0, but pull request #185 addresses this issue.
