### ISSUE TITLE
Is it possible to disable embedding entirely, even for ids?

### ISSUE THREAD

**Issue by dhruvg** [Shopify/identity_cache#197]
I notice this behavior when using the standard fetch call: 

````ruby
class User < ActiveRecord::Base
  include IdentityCache
  has_many :purchases
  cache_has_many :purchases
end
````

> User.fetch(1234)
User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1234 LIMIT 1
SELECT `purchases`.id FROM `purchases` WHERE `purchases`.`user_id` = 1234

**Why are associated purchase ids being fetched on a cache miss?**

In the `configuration_dsl.rb`, it seems `:embed` can only be set to `true` or `:ids`, which is the default. Why is this so? Why can we not fetch associations' ids and the payload on demand?

**Comment by dylanahsmith** [comment]
Originally `embed: false` was supported, but actually embedded ids, which is why the option was changed to `embed: :ids`.  I would like to properly implement `embed: false`, but no one has started to work on that yet.

**Comment by dhruvg** [comment]
Got it, thanks for clarifying.
