### ISSUE TITLE
cache_has_many only work with :embed => true

### ISSUE THREAD

**Issue by alefmeemseen** [Shopify/identity_cache#203]
I'm running rails 4.2.1 and I've setup identity_cache following the docs every thing working as expected until I tried to remove :embed => true or set it to false

I always get this output from rails console when run modle_instance.fetch_* 

```
NoMethodError: undefined method `fetch_multi' for #<Class:0x007f24099829a0>
from /home/ams/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
```

I even tried to downgrade rails to 4.1.9 and I get the same error . any help on that matter ? 

Thank you

**Comment by posgarou** [comment]
Same issue here with rails 4.2.2 using redis-rails as the cache store.

**Comment by dylanahsmith** [comment]
It looks like you just need to `include IdentityCache` in your associated class.  This isn't needed for embedding, since the record doesn't need to be fetched from the cache independently, but it is needed when only the id is embedded in the parent.
