### ISSUE TITLE
cache_index not updated

### ISSUE THREAD

**Issue by RobWu** [Shopify/identity_cache#212]
Hej,

I  have a cache_index on parent attributes
```ruby
    cache_index :parent_type, :parent_id, :unique => false
```

When i change the values the method ```fetch_by_parent_type_and_parent_id``` still returns me the wrong object. And the object get additonal added to the index with the new values.
That means I get the same object if I search for the new values & if i search for the obsolete values.

If i call ```:expire_cache``` on ```before_save:``` it works fine (As it uses old values to remove from index)

**Comment by dylanahsmith** [comment]
What version of rails and ar_transaction_changes are you using?  ar_transaction_changes 1.0.2 fixed a compatibility bug with rails 4.2.3 (https://github.com/dylanahsmith/ar_transaction_changes/commit/0f88370195bd68d45fdaa30b7c108018bde04e96).

**Comment by dylanahsmith** [comment]
Closing, since it sounds like this was an ar_transaction_changes issue which was fixed.
