### ISSUE TITLE
handle circular has_many, belongs_to associations

### ISSUE THREAD

**Issue by lrajlich** [Shopify/identity_cache#215]
models/asset.rb
```ruby
class Asset < ActiveRecord::Base
    include IdentityCache

    has_many        :custom_fields,            autosave: true
    cache_has_many  :custom_fields
end
```
models/custom_field.rb:
```ruby
class CustomField < ActiveRecord::Base
    include IdentityCache

    belongs_to :asset
    cache_belongs_to :asset
```

I need to require custom_field.rb in asset.rb otherwise I get this exception:
```
Uncaught exception: uninitialized constant Asset::CustomField
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/gems/activerecord-4.0.4/lib/active_record/inheritance.rb:129:in `compute_type'
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/gems/activerecord-4.0.4/lib/active_record/reflection.rb:178:in `klass'
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/bundler/gems/identity_cache-7a38bd64a5a5/lib/identity_cache/configuration_dsl.rb:234:in `build_id_embedded_has_many_cache'
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/bundler/gems/identity_cache-7a38bd64a5a5/lib/identity_cache/configuration_dsl.rb:110:in `cache_has_many'
	/Users/lukerajlich/Projects/dealpath/the_wall/models/asset.rb:7:in `<class:Asset>'
```

However, if I require custom_field
```
Uncaught exception: uninitialized constant CustomField::Asset
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/gems/activerecord-4.0.4/lib/active_record/inheritance.rb:129:in `compute_type'
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/gems/activerecord-4.0.4/lib/active_record/reflection.rb:178:in `klass'
	/Users/lukerajlich/.rvm/gems/ruby-2.1.2/bundler/gems/identity_cache-7a38bd64a5a5/lib/identity_cache/belongs_to_caching.rb:24:in `cache_belongs_to'
	/Users/lukerajlich/Projects/dealpath/the_wall/models/custom_field.rb:10:in `<class:CustomField>'
```

AFAIK, this is because identity_cache builds the association using ```klass``` on the association reflection which errors since either CustomField or Asset is not defined yet due to the circular nature of the relationship. The built-in has_many and belongs_to associations do not suffer from this issue.

We're using activerecord 4.0.4. I was able to reproduce the problem upgrading activerecord to 4.2.3.

**Comment by kulte** [comment]
This is a major issue. I've found this on a polymorphic belongs_to, but haven't checked for a non-polymorphic association. The ActiveRecord::Reflection instance variable `@klass` is nil when `.reflect_on_association(:association_name)` is called, I would assume that either it is not nil when the same class method is called on a non-polymorphic belongs_to, or the fact that when `#compute_type(class)` is called in ActiveRecord::Reflection that this issue is essentially rescued from and perhaps the issue with IdentityCache is that it cannot handle such occurrences as well. 

I'm going to continue to look into these and get some solid resolution on the guesses I've just made above, but either way this is a dead-end as is. When did IdentityCache add the BelongToCaching concern? Was this recent new functionality?

**Comment by lrajlich** [comment]
Thanks for the response @kulte - we've worked around by simply removing the cache_belongs_to association - we haven't run into any problems yet...

With activerecord associations, I noticed that they defer resolving the class and parse the associations DSL using a "Builder" class but I didn't look any further into it.
http://api.rubyonrails.org/classes/ActiveRecord/Associations/Builder.html

**Comment by lolownia** [comment]
I have also run into that issue, but with 
```
  # caching
  include IdentityCache
  cache_index :slug, :unique => true
  cache_has_many :decisions, :embed => true
```
when this class is loaded, Decision model is still not loaded (I checked it by running `Module.constants.select { |c| (eval c.to_s).is_a? Class }`, when `cache_has_many` is called.

This raises an error when `klass` is called in `build_recursive_association_cache`.

perhaps a solution would be to not instantly call klass method but hold HasManyReflection instance?

activerecord 4.2.0, identity_cache 0.2.5

**Comment by lolownia** [comment]
I have postponed calls to klass and this fixes the problem for me.
Please see https://github.com/lolownia/identity_cache/commit/31855fadff3889339b8d0ff844c5c90722eda402

I am not sure if this is a perfect solution performance-wise, perhaps klass call result should be cached later, when all the classes are loaded.
hope this helps

**Comment by lolownia** [comment]
Or... it does not fix the problem – I was to quick to report. But 
in configuration_dsl.rb:230  `add_parent_expiry_hook(options)` tries to call `klass`.

**Comment by lolownia** [comment]
I've created an issue #219 with a minimal example triggering this for your debugging pleasure :)
