### ISSUE TITLE
Support Redis

### ISSUE THREAD

**Issue by RobWu** [Shopify/identity_cache#22]
It would be great if it would be possible to used redis instead of memcached.

**Comment by lluchez** [comment]
I'll like to bring this gem into our system but we are currently using Redis and not Memcached.
Is here a way to have `identity_cache` work with Redis?

**Comment by dixpac** [comment]
@lluchez  something like this should work 👇 

```ruby
# initializers/identity_cache.rb
IdentityCache.cache_backend = ActiveSupport::Cache.lookup_store(*Rails.configuration.identity_cache_store)
```

```ruby
#config/environments/...
config.cache_store = :redis_cache_store, { url: ".. }
config.identity_cache_store = :redis_cache_store, { url: "..." }
```

We are using it in production and it works 👍
