### ISSUE TITLE
Memoization can cause multiple records to share an attributes hash

### ISSUE THREAD

**Issue by eugeneius** [Shopify/identity_cache#246]
When memoization is enabled, the same coder hash is used to instantiate multiple objects when a record is fetched multiple times. The data is passed to `#init_with` [without being duplicated](https://github.com/Shopify/identity_cache/blob/v0.2.5/lib/identity_cache/query_api.rb#L93), which also just [assigns the hash directly](https://github.com/rails/rails/blob/v4.2.5/activerecord/lib/active_record/core.rb#L303).

Here's a test case demonstrating how this behaviour caused a bug in our application: https://gist.github.com/e644d420da97dfc0b920

The `title` attribute is assigned on one record, but not saved. This updates the value in the attributes hash, but doesn't write it to the database. When the record is fetched again, it gets the same attributes hash, including the updated `title` attribute. We try to update the attribute on this new record, but the new value is the same as the existing one and Active Record optimises away the update.

This problem was actually fixed by #242, as the attributes hash is now duplicated every time a record is created. However the bug is still present in the latest released version, v0.2.5.

Since the worst case here is pretty bad (lost updates!) it would be great to either publish a new release from master to get the fix in #242, or do a bugfix release just to address this issue.

**Comment by camilo** [comment]
Sounds like #242 is on the latest release now.

**Comment by eugeneius** [comment]
:+1: thanks for following up, @camilo.

Do you think it's worthwhile adding the test case I wrote above to prevent this from regressing?

**Comment by camilo** [comment]
@eugeneius I think so yes, if you can turn it into a PR that'd be even better :)

**Comment by eugeneius** [comment]
It turns out this wasn't totally fixed by https://github.com/Shopify/identity_cache/pull/242 :grimacing: 

I've opened https://github.com/Shopify/identity_cache/pull/267 to fix the remaining case where this bug can happen.
