### ISSUE TITLE
Multiple cache backends

### ISSUE THREAD

**Issue by jingweno** [Shopify/identity_cache#254]
What do you think of supporting multiple cache adapters? We have different caching strategies for different models. Something like:

```rb
IdentityCache.cache_backend =  {
  in_memory: ActiveSupport::Cache.lookup_store(:memory_store),
  redis: ActiveSupport::Cache.lookup_store(:redis),
  default: ActiveSupport::Cache.lookup_store(:redis) # fetch by default from without specified
}
```

```rb
class Product < ActiveRecord::Base
  include IdentityCache
  cache_backend :redis # fetch from Redis
end

class User < ActiveRecord::Base
  include IdentityCache
  cache_backend :in_memory # fetch from in_memory
end
```

**Comment by dylanahsmith** [comment]
I don't see the use case. What is your motivation for wanting to do that?

Note that an in memory backend isn't suitable if you have multiple servers, since the servers wouldn't be able to invalidate each others cache when a record is modified.

**Comment by jingweno** [comment]
>  What is your motivation for wanting to do that?

Well, the motivation as mentioned is we have different caching strategies in the app: in memory store (mentioned below), thread local store (for current request), and Redis store for values that mutate the DBs. We would want to generalize the definitions of cache fields and cache keys with `identity_cache`.

> Note that an in memory backend isn't suitable if you have multiple servers, since the servers wouldn't be able to invalidate each others cache when a record is modified.

Our use case may be a bit special. We have some constants from DB that we want to load once and they never change. When the constants change, we restart the servers. The thinking is we can avoid route trip to external caching stores like Redis or Memcache.

**Comment by dylanahsmith** [comment]
It sounds like you could side-step a lot of the complexity that identity cache needs to worry about with cache invalidation.  Perhaps you can just use normal `@result ||=` memoization, `Rails.cache.fetch` or [frozen_record](https://rubygems.org/gems/frozen_record) depending on what type of data you are caching.

For instance, if you use Rails.cache.fetch, then you can just use the git sha for the current version in the key, and not have to worry about cache invalidation.

**Comment by camilo** [comment]
Closing feel free to re-open if further discussion is needed.

**Comment by dmitrypol** [comment]
First of all I want to say that I completely understand that open source maintainers have a life (work, family, etc).  And supporting different caching backend complicates things.  

But I do believe that supporting Redis could be very valuable.  Not so much as caching per model but caching for entire application (lots of people use Redis as cache backend).  

Just my $0.02

**Comment by dylanahsmith** [comment]
> But I do believe that supporting Redis could be very valuable. Not so much as caching per model but caching for entire application (lots of people use Redis as cache backend).

@dmitrypol You can use redis as a cache backend already.  However, if the cache backend doesn't support `cas` and `cas_multi` then it will use a fallback fetcher which has a race condition that can lead to cache corruption.

Redis supports [optimistic locking](http://redis.io/topics/transactions#optimistic-locking-using-check-and-set) which can be used to implement cas and cas_multi. That is what we did with https://rubygems.org/gems/memcached_store. If you could provide support for those in some gem, then we could link to that gem from this repo's README.

**Comment by dmitrypol** [comment]
Thank you for clarification.
