### ISSUE TITLE
Allow should_use_cache? to be overridden on a model

### ISSUE THREAD

**Issue by brettbevers** [Shopify/identity_cache#255]
The application that I'm working on uses database transactions to wrap actions that need to be cleanly rolled back in case of an error. There is a lot of static reference data that is retrieved within the transaction. I am using IdentityCache to cache this same reference data throughout the application, but the cache is intentionally not used when there is an open transaction. It would be ideal if I could configure this particular behavior per model. I've forked this repo and made some changed there that I believe accomplishes this (https://github.com/brettbevers/identity_cache/tree/allow-override-should-use-cache).  Can someone please look over my commit and point out any potential problems?

**Comment by juancaldera** [comment]
+1

**Comment by theturtle32** [comment]
:+1: +1

**Comment by dylanahsmith** [comment]
The idea sounds good to me.  Open up a pull request with your commit to make it easy to comment on the code.

**Comment by brettbevers** [comment]
Thanks @dylanahsmith !

**Comment by Sirupsen** [comment]
Fixed in https://github.com/Shopify/identity_cache/pull/291#issue-173330279
