### ISSUE TITLE
fetch returning RecordNotFound while find returns the right object

### ISSUE THREAD

**Issue by coffeebite** [Shopify/identity_cache#268]
I have a recurring issue where using `.fetch` returns `ActiveRecord::RecordNotFound` while `.find` returns the right object.

Any idea why this could be happening? Is there a way to setup identity_cache such that a RecordNotFound on `.fetch` automatically does a `.find` instead of returning a RecordNotFound?

**Comment by camilo** [comment]
> RecordNotFound on .fetch automatically does a .find instead of returning a RecordNotFound?

That is the default behaviour unless somehow you managed to poison your cache, keep in mind IDC does negative cacheing (caches nils).

What is the actual entry in memcached for those ids?

**Comment by coffeebite** [comment]
Thanks @camilo 

I upgraded to 3.1 and the problem went away, for the moment at least. If I see it again, I'll update the thread with the values in memcached.

**Comment by coffeebite** [comment]
Hey guys, 

This problem is coming back again. A fetch is returning nil while find returns the actual object. Any idea what could be poisoning the cache?

We are using the :dalli_store to store the identity_cache objects. Should we be using something else?

To give some context, before this resurfaced, one of our memcached boxes went down due to too many connections. 

Can that have an effect?

Also, is it posslbe that changing the hostnames of the two memcached boxes would poison the cache? We used to connect to our boxes via IPs. Now we do via hostnames (same boxes). I wonder if that messed things up.

**Comment by dylanahsmith** [comment]
> We are using the :dalli_store to store the identity_cache objects. Should we be using something else?

Yes, dalli_store doesn't have cas (check-and-set) support, so there is a race condition where if a record is being fetched and modified concurrently by different processes, then the fetch can populate the cache with old data.   We use the [memcached_store gem](https://rubygems.org/gems/memcached_store) which supports cas operations.

It looks like we are missing a warning about this in the README and the code.  The README even uses ActiveSupport::Cache::MemCacheStore as an example for configuring identity cache, which doesn't `.respond_to?(:cas)` or `.respond_to?(:cas_multi)` so it will use the fallback fetcher.  Having a warning if the fallback fetcher is used would make this mis-configuration easier to catch and make it easier to discover this problem when upgrading.

**Comment by dylanahsmith** [comment]
Opened https://github.com/Shopify/identity_cache/issues/295 with a proper description for the problem now that we know the source of it.

**Comment by coffeebite** [comment]
Thanks guys. 

Tried the memcached_store, can confirm that it is calling the cas methods. But we are still seeing issues where fetch returns nil but find returns a value.  And it is happening a lot.

Another thing — since moving to memcached_store, we are spending a lot more time in memcached, in the order of 25-40ms.

Trying to figure out what's causing this — could badly configured memcached cause this in any way? We are distributing load between two memcached servers. Would something like Twemproxy help?

**Comment by dylanahsmith** [comment]
Try using the `tcp_nodelay: true` configuration option
