### ISSUE TITLE
Non-integer primary keys

### ISSUE THREAD

**Issue by izzm** [Shopify/identity_cache#270]
If model uses non-integer primary key (UUID primary key for example) there is an id mismatch log entry like this:

```
[IdentityCache] (cache_backend) cache hit for IDC:6:blob:CustomerSession:16050426020716856423:caa8f134-0904-41dd-842d-8a574466a6a4
[IDC id mismatch] fetch_by_id_requested=caa8f134-0904-41dd-842d-8a574466a6a4 fetch_by_id_got=caa8f134-0904-41dd-842d-8a574466a6a4 
```

**Comment by dylanahsmith** [comment]
@camilo why did you close https://github.com/Shopify/identity_cache/issues/176 ?  Looks like this wasn't actually fixed, even though it is a simple fix.

**Comment by camilo** [comment]
Don't remember, I think it just looked stale.
