### ISSUE TITLE
Undefined identity_cache_store for Rails configuration

### ISSUE THREAD

**Issue by checkraiser** [Shopify/identity_cache#290]
Hi.
I've setup following README.
But i got the following error:

```
`method_missing': undefined method `identity_cache_store' for #<Rails::Application::Configuration:0x007ff3ed672080> (NoMethodError)
```

Here's my `initializers/cache_store.rb` :
```
IdentityCache.cache_backend = ActiveSupport::Cache.lookup_store(*Rails.configuration.identity_cache_store)
```

I'm using Rails 5.0.0.
Could you please help ?

**Comment by dylanahsmith** [comment]
Oh, it looks like we say to put `config.identity_cache_store = :mem_cache_store, Memcached::Rails.new(:servers => ["mem1.server.com"])` in environment/production.rb, but that actually needs to be assigned for all environments.

**Comment by camilo** [comment]
I updated the readme in #290 I'll close now, reopen if this is still an issue.
