### ISSUE TITLE
changed_attributes deprecation warning in Rails 5.1

### ISSUE THREAD

**Issue by desheikh** [Shopify/identity_cache#324]
ar_transaction_changes calls changed_attributes which is deprecated. Referencing the PR here in case someone else encounters this: https://github.com/dylanahsmith/ar_transaction_changes/pull/13

**Comment by dylanahsmith** [comment]
Looks like I should make a new release of ar_transaction_changes, since the new behaviour doesn't get this deprecation warning.

**Comment by dylanahsmith** [comment]
Made a v1.1.1 release of ar_transaction_changes, so upgrading to use that version will get rid of the deprecation warnings.
