### ISSUE TITLE
Dalli integration

### ISSUE THREAD

**Issue by saiqulhaq** [Shopify/identity_cache#462]
on the readme, it says we have to use memcached_store. however I found that Dalli also has CAS support. what should we do to make Dalli can work with Identity Cache gem?

**Comment by dylanahsmith** [comment]
It doesn't look like active support's ActiveSupport::Cache::MemCacheStore provides CAS support or exposes the underlying Dalli::Client instance, so I think we need to add CAS support to active support if we want to integrate with ActiveSupport::Cache::MemCacheStore.

Alternatively, we can provide a cache adapter that integrates with a Dalli::Client instance directly.  The cache adapter will be used by [IdentityCache::CacheFetcher](https://github.com/Shopify/identity_cache/blob/fd2f3164bc21b50e69b6be5ef54e983c74edcf31/lib/identity_cache/cache_fetcher.rb) if it provides `cas` and `cas_multi` methods that behave like those provided by the memcached_store gem.  In addition to those methods, it will also need to provide a `write` method that behaves like ActiveSupport::Cache::Store.

**Comment by saiqulhaq** [comment]
https://github.com/Shopify/identity_cache/pull/465
